title: <p align="center"> Rajesh R </p>
logo: /assets/img/profolio.jpg

description:
  <p align="center">
  <a href="linkedin.com/in/ramesh-rajesh-">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working as Java Full Stack Developer.
  Working with Infosys for 2+ years.
  <br>
  </p>
theme: jekyll-theme-minimal
